version: '2'
services:
    stackservice-app:
        image: stackservice
        external_links:
            - stackservice-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/StackService
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    stackservice-postgresql:
        extends:
            file: postgresql.yml
            service: stackservice-postgresql
